version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    ignore:
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
